---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng-secrets
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_SECRET: AgBZjBakPinV0b85RaVCArKjwMW3l3uPIAhXQ5lzXozXouglAsCNc6mCf/SVSSteesjCgNqYDBNG/+YEe1HxCgf9YN8faQtranYMaB/v4HmG3bFX3elkZn0IUK+usKXwOdV52whnq5CVpF+ZQ9/vplp6egbXZDRLlz2/G9BQ/jC8vLx8ibyWAt9iZnbFNf2koVoaobA/+mc/7uZl5M45JWYwSMvkMDwc0YQpYJMIT6R0EWwSuxzhKG4v6DnaoPzizpe5OXR9Nu3Z2P+migw1mPhwB0d5A86lKCpBgEjWtbPyJMu9kdvj82tW59zg5BgsAxtnySEO0Fw/TGc0ZHBu6THrIhlUMqrKXqcclXFlZjhpxFE75R6HWRgDOP+H+G8X+FnYQQPf9/M719iaJVS6FxwuDZ7gSrKzxOQeyHNTBJyBeDhWpzqfCLObVps9lFgJdeocRDSNfu+Pg/RewXlWuGO25M5pWsTQrnKOPuMRHvz2Im1ePxHnzqmu3O8vYnlfXfWF7RHDsdTQF9zdAi8Cifa1FIoba6RDMCqHavNVS8kv/f2foWeVQnZYc67MB8UMtGRECREqZbK+b4mL2GCoEY/lMkkn+0tlDBD9iNYxc1kmlbP9+oGXxAW3gi9jbR8ynsShzY76Ve3LwIvRJF/c/iRDeIW/iN/V4U2+59QdiE4lZh15pfg+NNU/4WgQfEXVnNmJhDFGzH0ZfZROpC4pUn/FDxe3Ug7wlXVs5fdf9HocPw==
  template:
    metadata:
      creationTimestamp: null
      name: searxng-secrets
      namespace: searxng
    type: Opaque
