---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hf-secret
  namespace: vllm
spec:
  encryptedData:
    TOKEN: AgC6tQumjfxg3zchzH8qPBIBHONT6EfvBK+5vXd/k2Y3Gc9rZ/zUPxxbosOWahX6i3Prbv15XG5+nCZjwwVH++uFINpFGzGKN6+KSgJlvmI04M3C14UM2Q3NYDg5BzBiVTM1iiS3DGlEn2yyU+uy3SaseqsXuBLnNXYDDkrmlyuXyQMf/pCRwdNJ9ldexwKGNKW6kAJJQfbZOyjwAxPkXBnW9gEJjLw7I6T8wjQHEd1Tw+8kz0VMRFcAy07ObKGqBu5OIbm50yDkcQkLYPrH8yW6cUPXnr66Qj+lGKwNaY8jO9mj4OnJDFYNP+PNsErw/t60QnQFcziQcV05fI5V9PJndM+LRxEPZQpy7P58lWUaysiK0tI0PNmRg0Jo/MLb5ZXXT9JayttCJDbAwqY7R1kAvE72vnmi5cFezhpMafq/LCeZ5kq9RH8MgN8t+ACO3LuEVjSFcgmDnWP17NHH9NJ9i70jRuyoHPR+aOgHc0WfDX1yVJhHJTIpU0AtR6vFcHkOJarbRwbvL8BER2Fq04yYAJ9vOBxUzIxELQn+sA01oLFYzHYXWlr3vOAEqdVwWDc+jWLoOgrWnIrp6ty34tIoWaThSGI98zCk436ozGjSoYf4GMrqxN1zGW7WWaJQqU0wMawVOXlyx7MebtooKXEKx8Ersv3aFjaOIkfjG6VWEoPdkOMllEKMfCFiNqViR3r6+2tKi8u8Hp/A1BF92wP6hUNY2+NU794ermMJjodegT0mbZ6q
  template:
    metadata:
      creationTimestamp: null
      name: hf-secret
      namespace: vllm
    type: Opaque
