---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudnative-pg-cluster-admin
  namespace: os2adgang
spec:
  encryptedData:
    password: AgBdyTLoSEsQiGuA7zeIAFr8lUq9v0LvOEa8eTE4DiUFzVKZ25JIZwkswg1Dbc2uYNPeZ+KhTCvJNs34slX+AtAvXfCUwHTgQhoNWbtyYn5fuxEtAf+8t8aWDyUG6Q/qxffsCKqurqbdnuJHqD373XdUE4F/GNrzaJZRfj6y5JcvbVHI5nZpsdPK3G3qbU8/OALXcwCmujF1iK7ccUTSRdvZ3oIQELXvp4sERN6WrB4tTiZThZ13msxMRmEHvWL/pklpj5rGoV16k0vjFFFk87OeFm/mnacwTEarG+J4YrfVEJyE/QpyGUQCDvDxmUbbU+vY2NcpUfhhw5DjbjfUeMOmkMrgC+fftDl6XmJPExC1CoIMM5Z58bedSy2R5V7dbR1YS6yIY8bBi872kJbj0MDQj6tJ+59Wh3K4T2bPsQO7BGFjCtJqjyZqkOVMlO/9X/QWaiMxFWOM6HhArpcene8g10P7BLI274ioK4ZVbL86Y77S8LQK+X5r1aZjbXnI9TvxmApESLxhdLbmMVmbcEBCdt/Yr3T9fWhEzKVkTUVsHK6a/TS34hbipnw8k7iupC0rfHVusuqlScaN5Np9+6hyYFW/lcTZ8Yq6peldpRxqLYpIGqYXnQsuJlptxWfGAWbDr0EptxsKRtzJ4nH8qCZ1i9oynNy3x7uebcGk1+MJdlC+t/L8Di/RS1FYu29Dza7vLKpHJtl/mfURV9q1bq0hZV+/XuwBKys7pmYZMBBMEw972iHiVtBZvr7WfdCdtXFQpU4vB1w0SAc15+upGsrv
    username: AgAfrvVqR16vqVpbKwpJefqNa+PCqiiyYmtLjcfHD2GaGcSpwVrcsPROe+LG9IDjLn6JZ3kmypom8lcZDCwVanCxuY8+hFAyRvPib2kJW0r7cB5V0ygugtr9Zd9WCcQmdrDA4VdeaoUX5STEj09Q06EyaNtXJJ65/mDJGT8lD8B6SlUZUu1Upw9X/2pTUMLSBBCflJ5zX5scdbkrCWNAyBH/zMu5GKfeti5oXXOEazhYodywtdStGOI7l8EiKouQzqXsqUnO7nqJUlN4775oVuKcZKjBdTxEB9OJMxlEC4hrWNh5hdiXDnI3mT8f9fdkB3bAfJpN45iZn39L+KUZ3lLZXM4fQRPeR9Bx9Jk3vjDbtTRj/pMLoZaGSEaBmz0BH5UDEQy3h1MrDF3DCZKLLDx1KI0iMUYmwfcuPDl2xY9aj4oEcCqWwHHv8pvU7Ttw9bV0uwbH/bH6mMHnuziFfd+KSXQokSY8vJQ3DLDMdEDwu5r9mKzR4gyL3pGaTu74c920G6ojYVw54LxhbXY2IwXdRR8UoSqJk6hDlR1IDtdz1SZVWR8Hw7n5Jhom3rlf3gIK5M4F0XG7IFKglmlHCLyHQZ9Rdat/3HhC45iaPmcIDB9TFqm72o2z3XUaXLtp1WVThYn68gkNJQlDUqBun6Xe/XexvuV/bODEcGUXVJFsUpq5BRAsN+K5y22+H5yZmhEArlM75w==
  template:
    metadata:
      creationTimestamp: null
      name: cloudnative-pg-cluster-admin
      namespace: os2adgang
    type: Opaque
