apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: litellm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  name: litellm
  owner: litellm
  cluster:
    name: cloudnative-pg-cluster
