---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-secrets
  namespace: litellm
spec:
  encryptedData:
    CA_VLLM_LOCAL_API_KEY: AgCWHlfCxbQPHDdBfsNJrVCpfO8p0ZeMaOyt2XD8Em6CMVKVosTepDO6I0krcjMdXiC/veRsCs0ob5TwHlspr8GgCEXzqbaorN2WS182DtMWOeoieIF7rgePPlSWqPbNaapDyDjdgxd+vVOcOHkcTTyQ683kiSkSn2F+7VeYaWxZNJ70rfyA05tjBTRAlxbqLKDI5QTNWtK85yq4BgQ705n9hjiSoxffq3/igcM7UUsgWwi2oXhT5T79WMStb3cMpk0rVxL103wocYZ2OaAPNv2+JKVbluIMNDiYSejpzztFSeOq/0Pt/axKvOvgxdrCybwd9fQqeIFXJdHDThyDMhAfk217ELiV5DqvEgwPOI6kIEed+Crky6Gzpkb/YQNRnZRFXVwoNk07e84CPE0MRUNvRcrbwFF2L6NzQmqrABngKK6+g7RVDhOnBRGX7eo39ePMA/QWr4bzoBVKzN3JSTjY/rZwiaGxc15dZ6iw2AF6kDRGgy/PlMOxih7lW3rDGChZeKkCxYRrSMkRAEVLGIsjgkhQ+SwW7r7WSjam7ksG0dC8esPfCeApY0kxE73Jl4aTqt1FW0Cr+flhkbHcfwzoVgPV2efqYswrFisc+FKGeUMtahAk5BIpYXviZiqlRNqnbIe8P47K0KLGLbjVeCays5MhnT2vcNk/AmJ35PKwLok1Ck1R2x4U2d8wJs1hQefkik3RFDYoo8KiWy4YZHNbhclsgNeCV1nHgLA0X7B24g==
    PROXY_MASTER_KEY: AgC2J/Xv/povsiCyZkgMG92587WtC6IsRAPr4x0LIsPo2KaEC/09RMp70zX/Gw0cVK6KFP5HbXCwiwgEMuF1opHjQvd5AXONH9WtuPeHiaZjOmZzTuI1WMRXJq8jxC2qAJrveKt4P1cxb06LKpx3u8QblMP7CO90Yb3x0a5L5ly+1XVaDrjLnP0B9WxV9qzEo8nP1xYgDWYNSX91Z8+rVo5gnlh9jK/RYRJpPVCCmmXB8JQAHubYfD1xwcMME/tc5wPr0wUALdfZHHp8vtreK+LXaRytzec0BvQF0A9VElNIdzNIZh6pB7pnxm9oWPg1EP3W7JNN1OKPC2Jf+XJuPkBe0gpXbn4VvIvJlcRZ4So36TSqlQ4/xcB1oXBCgEpDNKdNN91Xi9WcHw9ylH+Av1cyxq27hgkrA5Y/G3vGjfGxofcxFwLAzHnQtMLdjimGXMmjf6KwGSgQBAjvHHxgbD7UwaHk8z7bXBLWRObZCmyEX+sviRk5ArCWmmkzJFPV67pFHDkrb+i16gSdR3nhvs6g0yDkITOUa1Hm0guQRMzhV7OiNIsDbdIxui6tXUdoJgP4ajgSsIcr3sahSymRamC388C7nn4Z7/e3A5lwnfjgZCb1/p6kk133yidApaPxyJAud3ke0rEaInT8/fc/SGdfilNXojgIiSLTVtL9ofGgwB8o+TGJHVlS2ehBMqzp8m7FOxtiUTCJ7enF0IC++efnsEUUfSR5ff19YQVjCsJ66Q==
  template:
    metadata:
      creationTimestamp: null
      name: litellm-secrets
      namespace: litellm
    type: Opaque
